export function getDefaultClientData() {
    return {
        hardware: {
            cpu: "Arm Cortex-A76",
            ram: 16,
            gpu: "VideoCore VII GPU",
            battery_life_in_min: 60,
        },
        user_chat_history: [],
        user_sensitivity: {
            energy: 5,
            latency: 5,
            accuracy: 5,
        },
        quantization_levels: {
            4: {
                benefit: 10,
                cost: 10,
            },
            8: {
                benefit: 30,
                cost: 20,
            },
            16: {
                benefit: 50,
                cost: 40,
            },
            32: {
                benefit: 60,
                cost: 80,
            },
        }
    }
}

export const SUPPORTED_CPU_LIST = [
    "ARM Cortex-M0",
    "ARM Cortex-M0+",
    "ARM Cortex-M1",
    "ARM Cortex-M3",
    "ARM Cortex-M4",
    "ARM Cortex-M7",
    "ARM Cortex-M23",
    "ARM Cortex-M33",
    "ARM Cortex-M35P",
    "ARM Cortex-M55",
    "ARM Cortex-A5",
    "ARM Cortex-A7",
    "ARM Cortex-A8",
    "ARM Cortex-A9",
    "ARM Cortex-A53",
    "ARM Cortex-A55",
    "ARM Cortex-A72",
    "ARM Cortex-A73",
    "ARM Cortex-A75",
    "ARM Cortex-A76",
    "Intel Atom E3800",
    "Intel Quark SE",
    "Intel Quark D2000",
    "Intel Quark X1000",
    "RISC-V RV32IMAC",
    "RISC-V RV64IMAC",
    "ESP8266",
    "ESP32",
    "ESP32-S2",
    "ESP32-S3",
    "ESP32-C3",
    "ESP32-H2",
    "NXP i.MX 6",
    "NXP i.MX 7",
    "NXP i.MX 8",
    "NXP i.MX RT",
    "Qualcomm Snapdragon 410E",
    "Qualcomm Snapdragon 600E",
    "Qualcomm Snapdragon 820E",
    "Raspberry Pi RP2040",
    "Broadcom BCM2835",
    "Broadcom BCM2836",
    "Broadcom BCM2837",
    "Broadcom BCM2711",
    "Texas Instruments MSP430",
    "Texas Instruments Sitara AM335x",
    "Texas Instruments Sitara AM437x",
    "Microchip PIC32",
    "Microchip SAMD21",
    "Microchip SAMD51",
    "STMicroelectronics STM32F0",
    "STMicroelectronics STM32F1",
    "STMicroelectronics STM32F2",
    "STMicroelectronics STM32F3",
    "STMicroelectronics STM32F4",
    "STMicroelectronics STM32F7",
    "STMicroelectronics STM32H7",
    "STMicroelectronics STM32L0",
    "STMicroelectronics STM32L1",
    "STMicroelectronics STM32L4",
    "STMicroelectronics STM32L5",
    "STMicroelectronics STM32G0",
    "STMicroelectronics STM32G4",
    "STMicroelectronics STM32WB",
    "STMicroelectronics STM32WL",
    "Nordic nRF51",
    "Nordic nRF52",
    "Nordic nRF53",
    "Nordic nRF91",
    "Silicon Labs EFM32",
    "Silicon Labs EFR32",
    "Allwinner A10",
    "Allwinner A20",
    "Allwinner A33",
    "Allwinner H3",
    "Allwinner H5",
    "Allwinner H6",
    "AMD G-Series GX-210HA",
    "AMD G-Series GX-412HC",
    "AMD G-Series GX-415GA",
    "AMD G-Series GX-420CA",
    "AMD G-Series GX-424CC",
    "AMD Ryzen Embedded V1000",
    "AMD Ryzen Embedded R1000",
    "AMD EPYC Embedded 3000",
    "Xilinx Zynq-7000",
    "Xilinx Zynq UltraScale+",
    "Xilinx Zynq UltraScale+ MPSoC",
    "Xilinx Zynq UltraScale+ RFSoC",
    "Xilinx Artix-7",
    "Xilinx Kintex-7",
    "Xilinx Virtex-7",
    "Xilinx Spartan-7",
    "Xilinx Versal",
    "Xilinx Versal AI Core",
    "Xilinx Versal Prime",
    "Xilinx Versal Premium",
    "Xilinx Versal HBM",
    "Xilinx Versal AI Edge",
    "Xilinx Versal AI RF",
    "Xilinx Versal AI RFSoC",
    "Xilinx Versal AI RFSoC+"
]


export const SUPPORTED_GPU_LIST = [
    "Jetson Nano (128-core Maxwell GPU)",
    "Jetson TX1 (256-core Maxwell GPU)",
    "Jetson TX2 (256-core Pascal GPU)",
    "Jetson Xavier NX (384-core Volta GPU with 48 Tensor Cores)",
    "Jetson AGX Xavier (512-core Volta GPU with 64 Tensor Cores)",
    "Jetson Orin Nano (512-core Ampere GPU)",
    "Jetson AGX Orin (2048-core Ampere GPU)",
    "Tegra X1 (256-core Maxwell GPU)",
    "Tegra X2 (256-core Pascal GPU)",
    "Mali-G52 (Used in low-power IoT devices)",
    "Mali-G57 (Mid-range, used in IoT and edge devices)",
    "Mali-G68 (Higher performance for IoT and embedded applications)",
    "Mali-G710 (High-end, used in advanced IoT and edge computing)",
    "PowerVR Series8XE (Ultra-low power for IoT and embedded devices)",
    "PowerVR Series9XMP (Mid-range for IoT and edge computing)",
    "PowerVR Series9XEP (Low-power for IoT and embedded systems)",
    "Adreno 504 (Used in low-power IoT devices)",
    "Adreno 506 (Mid-range for IoT and edge computing)",
    "Adreno 612 (Higher performance for IoT applications)",
    "Adreno 620 (Used in advanced IoT and edge devices)",
    "Intel HD Graphics (Low-power, used in Intel Atom and Celeron processors for IoT)",
    "Intel UHD Graphics (Used in Intel Core processors for edge computing)",
    "Intel Iris Xe Graphics (Higher performance for advanced IoT applications)",
    "AMD Radeon E8860 (Mid-range for embedded and IoT applications)",
    "AMD Radeon E9170 (Low-power for IoT and edge devices)",
    "AMD Radeon RX Embedded Series (Higher performance for advanced IoT and edge computing)",
    "Vivante GC7000 Series (Low-power for IoT devices)",
    "Vivante GC8000 Series (Mid-range for IoT and embedded applications)",
    "VideoCore IV (Used in Raspberry Pi and other IoT devices)",
    "VideoCore VI (Higher performance for IoT and embedded systems)",
    "Synaptics Dolphin GPU (Used in low-power IoT devices)",
    "VeriSilicon GPU IP (Licensed for use in IoT and embedded systems)",
    "Think Silicon NEMA GPU (Ultra-low power for IoT and wearables)"
];
